# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oyin10.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    #O'zgaruvchilar
    hammsiUchun1 = ""
    list = []
    birinchi = ""
    toq = []
    juft = []



    #------------------------------------------
    #line for 1
    def Garizontal1(self):
        self.hammsiUchun1 = self.button1_1.text()
        self.button1_1.setText(self.button1_2.text())
        self.button1_2.setText(self.button1_3.text())
        self.button1_3.setText(self.button1_4.text())
        self.button1_4.setText(self.button1_5.text())
        self.button1_5.setText(self.button1_6.text())
        self.button1_6.setText(self.button1_7.text())
        self.button1_7.setText(self.button1_8.text())
        self.button1_8.setText(self.hammsiUchun1)

    #line for 2
    def Garizontal2(self):
        self.hammsiUchun1 = self.button2_1.text()
        self.button2_1.setText(self.button2_2.text())
        self.button2_2.setText(self.button2_3.text())
        self.button2_3.setText(self.button2_4.text())
        self.button2_4.setText(self.button2_5.text())
        self.button2_5.setText(self.button2_6.text())
        self.button2_6.setText(self.button2_7.text())
        self.button2_7.setText(self.button2_8.text())
        self.button2_8.setText(self.hammsiUchun1)

        #line for 3
    def Garizontal3(self):
        self.hammsiUchun1 = self.button3_1.text()
        self.button3_1.setText(self.button3_2.text())
        self.button3_2.setText(self.button3_3.text())
        self.button3_3.setText(self.button3_4.text())
        self.button3_4.setText(self.button3_5.text())
        self.button3_5.setText(self.button3_6.text())
        self.button3_6.setText(self.button3_7.text())
        self.button3_7.setText(self.button3_8.text())
        self.button3_8.setText(self.hammsiUchun1)

    #line for 4
    def Garizontal4(self):
        self.hammsiUchun1 = self.button4_1.text()
        self.button4_1.setText(self.button4_2.text())
        self.button4_2.setText(self.button4_3.text())
        self.button4_3.setText(self.button4_4.text())
        self.button4_4.setText(self.button4_5.text())
        self.button4_5.setText(self.button4_6.text())
        self.button4_6.setText(self.button4_7.text())
        self.button4_7.setText(self.button4_8.text())
        self.button4_8.setText(self.hammsiUchun1)

    #line for 5
    def Garizontal5(self):
        self.hammsiUchun1 = self.button5_1.text()
        self.button5_1.setText(self.button5_2.text())
        self.button5_2.setText(self.button5_3.text())
        self.button5_3.setText(self.button5_4.text())
        self.button5_4.setText(self.button5_5.text())
        self.button5_5.setText(self.button5_6.text())
        self.button5_6.setText(self.button5_7.text())
        self.button5_7.setText(self.button5_8.text())
        self.button5_8.setText(self.hammsiUchun1)

    #line for 6
    def Garizontal6(self):
        self.hammsiUchun1 = self.button6_1.text()
        self.button6_1.setText(self.button6_2.text())
        self.button6_2.setText(self.button6_3.text())
        self.button6_3.setText(self.button6_4.text())
        self.button6_4.setText(self.button6_5.text())
        self.button6_5.setText(self.button6_6.text())
        self.button6_6.setText(self.button6_7.text())
        self.button6_7.setText(self.button6_8.text())
        self.button6_8.setText(self.hammsiUchun1)

    #line for 7
    def Garizontal7(self):
        self.hammsiUchun1 = self.button7_1.text()
        self.button7_1.setText(self.button7_2.text())
        self.button7_2.setText(self.button7_3.text())
        self.button7_3.setText(self.button7_4.text())
        self.button7_4.setText(self.button7_5.text())
        self.button7_5.setText(self.button7_6.text())
        self.button7_6.setText(self.button7_7.text())
        self.button7_7.setText(self.button7_8.text())
        self.button7_8.setText(self.hammsiUchun1)

    #line for 8
    def Garizontal8(self):
        self.hammsiUchun1 = self.button8_1.text()
        self.button8_1.setText(self.button8_2.text())
        self.button8_2.setText(self.button8_3.text())
        self.button8_3.setText(self.button8_4.text())
        self.button8_4.setText(self.button8_5.text())
        self.button8_5.setText(self.button8_6.text())
        self.button8_6.setText(self.button8_7.text())
        self.button8_7.setText(self.button8_8.text())
        self.button8_8.setText(self.hammsiUchun1)

    #-----------------------------------------------------
    #line for v1
    def Vertikal1(self):
        self.hammsiUchun1 = self.button1_1.text()
        self.button1_1.setText(self.button2_1.text())
        self.button2_1.setText(self.button3_1.text())
        self.button3_1.setText(self.button4_1.text())
        self.button4_1.setText(self.button5_1.text())
        self.button5_1.setText(self.button6_1.text())
        self.button6_1.setText(self.button7_1.text())
        self.button7_1.setText(self.button8_1.text())
        self.button8_1.setText(self.hammsiUchun1)

    #line for v2
    def Vertikal2(self):
        self.hammsiUchun1 = self.button1_2.text()
        self.button1_2.setText(self.button2_2.text())
        self.button2_2.setText(self.button3_2.text())
        self.button3_2.setText(self.button4_2.text())
        self.button4_2.setText(self.button5_2.text())
        self.button5_2.setText(self.button6_2.text())
        self.button6_2.setText(self.button7_2.text())
        self.button7_2.setText(self.button8_2.text())
        self.button8_2.setText(self.hammsiUchun1)

    #line for v3
    def Vertikal3(self):
        self.hammsiUchun1 = self.button1_3.text()
        self.button1_3.setText(self.button2_3.text())
        self.button2_3.setText(self.button3_3.text())
        self.button3_3.setText(self.button4_3.text())
        self.button4_3.setText(self.button5_3.text())
        self.button5_3.setText(self.button6_3.text())
        self.button6_3.setText(self.button7_3.text())
        self.button7_3.setText(self.button8_3.text())
        self.button8_3.setText(self.hammsiUchun1)

    #line for v4
    def Vertikal4(self):
        self.hammsiUchun1 = self.button1_4.text()
        self.button1_4.setText(self.button2_4.text())
        self.button2_4.setText(self.button3_4.text())
        self.button3_4.setText(self.button4_4.text())
        self.button4_4.setText(self.button5_4.text())
        self.button5_4.setText(self.button6_4.text())
        self.button6_4.setText(self.button7_4.text())
        self.button7_4.setText(self.button8_4.text())
        self.button8_4.setText(self.hammsiUchun1)

    #line for v5
    def Vertikal5(self):
        self.hammsiUchun1 = self.button1_5.text()
        self.button1_5.setText(self.button2_5.text())
        self.button2_5.setText(self.button3_5.text())
        self.button3_5.setText(self.button4_5.text())
        self.button4_5.setText(self.button5_5.text())
        self.button5_5.setText(self.button6_5.text())
        self.button6_5.setText(self.button7_5.text())
        self.button7_5.setText(self.button8_5.text())
        self.button8_5.setText(self.hammsiUchun1)

    #line for v6
    def Vertikal6(self):
        self.hammsiUchun1 = self.button1_6.text()
        self.button1_6.setText(self.button2_6.text())
        self.button2_6.setText(self.button3_6.text())
        self.button3_6.setText(self.button4_6.text())
        self.button4_6.setText(self.button5_6.text())
        self.button5_6.setText(self.button6_6.text())
        self.button6_6.setText(self.button7_6.text())
        self.button7_6.setText(self.button8_6.text())
        self.button8_6.setText(self.hammsiUchun1)

    #line for v7
    def Vertikal7(self):
        self.hammsiUchun1 = self.button1_7.text()
        self.button1_7.setText(self.button2_7.text())
        self.button2_7.setText(self.button3_7.text())
        self.button3_7.setText(self.button4_7.text())
        self.button4_7.setText(self.button5_7.text())
        self.button5_7.setText(self.button6_7.text())
        self.button6_7.setText(self.button7_7.text())
        self.button7_7.setText(self.button8_7.text())
        self.button8_7.setText(self.hammsiUchun1)
    
    #line for v8
    def Vertikal8(self):
        self.hammsiUchun1 = self.button1_8.text()
        self.button1_8.setText(self.button2_8.text())
        self.button2_8.setText(self.button3_8.text())
        self.button3_8.setText(self.button4_8.text())
        self.button4_8.setText(self.button5_8.text())
        self.button5_8.setText(self.button6_8.text())
        self.button6_8.setText(self.button7_8.text())
        self.button7_8.setText(self.button8_8.text())
        self.button8_8.setText(self.hammsiUchun1)

    #------------------------------------------------------

    #bu faqat 2tomoni bor button uchun
    def Button2Uchun(self,ozi,ong,past):
        if(ozi.text() != ""):
            self.list.append("1")
            for i in range(1,300,2):
                self.toq.append(i)
            for j in range(2,300,2):
                self.juft.append(j)
            if(len(self.list) in self.toq):
                self.birinchi = ozi.text()#self.button1_2.text()
            elif(len(self.list) in self.juft):
                if(int(ozi.text())+int(self.birinchi) == 10):
                    if(ong.text() == self.birinchi):
                        ong.setText("")
                        ozi.setText("")
                    elif(past.text() == self.birinchi):
                        past.setText("")
                        ozi.setText("") 
        if(self.button1_1.text() == "" and self.button1_2.text() == "" and self.button1_3.text() == "" and self.button1_4.text() == "" and
           self.button1_5.text() == "" and self.button1_6.text() == "" and self.button1_7.text() == "" and self.button1_8.text() == "" and
           self.button2_1.text() == "" and self.button2_2.text() == "" and self.button2_3.text() == "" and self.button2_4.text() == "" and
           self.button2_5.text() == "" and self.button2_6.text() == "" and self.button2_7.text() == "" and self.button2_8.text() == "" and
           self.button3_1.text() == "" and self.button3_2.text() == "" and self.button3_3.text() == "" and self.button3_4.text() == "" and
           self.button3_5.text() == "" and self.button3_6.text() == "" and self.button3_7.text() == "" and self.button3_8.text() == "" and
           self.button4_1.text() == "" and self.button4_2.text() == "" and self.button4_3.text() == "" and self.button4_4.text() == "" and
           self.button4_5.text() == "" and self.button4_6.text() == "" and self.button4_7.text() == "" and self.button4_8.text() == "" and
           self.button5_1.text() == "" and self.button5_2.text() == "" and self.button5_3.text() == "" and self.button5_4.text() == "" and
           self.button5_5.text() == "" and self.button5_6.text() == "" and self.button5_7.text() == "" and self.button5_8.text() == "" and
           self.button6_1.text() == "" and self.button6_2.text() == "" and self.button6_3.text() == "" and self.button6_4.text() == "" and
           self.button6_5.text() == "" and self.button6_6.text() == "" and self.button6_7.text() == "" and self.button6_8.text() == "" and
           self.button7_1.text() == "" and self.button7_2.text() == "" and self.button7_3.text() == "" and self.button7_4.text() == "" and
           self.button7_5.text() == "" and self.button7_6.text() == "" and self.button7_7.text() == "" and self.button7_8.text() == "" and
           self.button8_1.text() == "" and self.button8_2.text() == "" and self.button8_3.text() == "" and self.button8_4.text() == "" and
           self.button8_5.text() == "" and self.button8_6.text() == "" and self.button8_7.text() == "" and self.button8_8.text() == ""):
            self.Oyna.setText("Siz yutdingiz!")

    def Button_1_1(self):
        self.Button2Uchun(self.button1_1, self.button1_2, self.button2_1)
    def Button_1_8(self):
        self.Button2Uchun(self.button1_8, self.button1_7, self.button2_8)
    def Button_8_1(self):
        self.Button2Uchun(self.button8_1, self.button8_2, self.button7_1)
    def Button_8_8(self):
        self.Button2Uchun(self.button8_8, self.button8_7, self.button7_8)
    #2tomonlilar tugadi
    #-------------------------------------------------------------------


    #bu faqat 3tomoni bor button uchun
    def Button3Uchun(self,ozi,ong,chap,past):
        if(ozi.text() != ""):
            self.list.append("1")
            for i in range(1,300,2):
                self.toq.append(i)
            for j in range(2,300,2):
                self.juft.append(j)
            if(len(self.list) in self.toq):
                self.birinchi = ozi.text()#self.button1_2.text()
            elif(len(self.list) in self.juft):
                if(int(ozi.text())+int(self.birinchi) == 10):
                    if(ong.text() == self.birinchi):
                        ong.setText("")
                        ozi.setText("")
                    elif(chap.text() == self.birinchi):
                        chap.setText("")
                        ozi.setText("")
                    elif(past.text() == self.birinchi):
                        past.setText("")
                        ozi.setText("")
        if(self.button1_1.text() == "" and self.button1_2.text() == "" and self.button1_3.text() == "" and self.button1_4.text() == "" and
           self.button1_5.text() == "" and self.button1_6.text() == "" and self.button1_7.text() == "" and self.button1_8.text() == "" and
           self.button2_1.text() == "" and self.button2_2.text() == "" and self.button2_3.text() == "" and self.button2_4.text() == "" and
           self.button2_5.text() == "" and self.button2_6.text() == "" and self.button2_7.text() == "" and self.button2_8.text() == "" and
           self.button3_1.text() == "" and self.button3_2.text() == "" and self.button3_3.text() == "" and self.button3_4.text() == "" and
           self.button3_5.text() == "" and self.button3_6.text() == "" and self.button3_7.text() == "" and self.button3_8.text() == "" and
           self.button4_1.text() == "" and self.button4_2.text() == "" and self.button4_3.text() == "" and self.button4_4.text() == "" and
           self.button4_5.text() == "" and self.button4_6.text() == "" and self.button4_7.text() == "" and self.button4_8.text() == "" and
           self.button5_1.text() == "" and self.button5_2.text() == "" and self.button5_3.text() == "" and self.button5_4.text() == "" and
           self.button5_5.text() == "" and self.button5_6.text() == "" and self.button5_7.text() == "" and self.button5_8.text() == "" and
           self.button6_1.text() == "" and self.button6_2.text() == "" and self.button6_3.text() == "" and self.button6_4.text() == "" and
           self.button6_5.text() == "" and self.button6_6.text() == "" and self.button6_7.text() == "" and self.button6_8.text() == "" and
           self.button7_1.text() == "" and self.button7_2.text() == "" and self.button7_3.text() == "" and self.button7_4.text() == "" and
           self.button7_5.text() == "" and self.button7_6.text() == "" and self.button7_7.text() == "" and self.button7_8.text() == "" and
           self.button8_1.text() == "" and self.button8_2.text() == "" and self.button8_3.text() == "" and self.button8_4.text() == "" and
           self.button8_5.text() == "" and self.button8_6.text() == "" and self.button8_7.text() == "" and self.button8_8.text() == ""):
            self.Oyna.setText("Siz yutdingiz!")

    def Button_1_2(self):
        self.Button3Uchun(self.button1_2, self.button1_1, self.button1_3, self.button2_2)
    def Button_1_3(self):
        self.Button3Uchun(self.button1_3, self.button1_2, self.button1_4, self.button2_3)
    def Button_1_4(self):
        self.Button3Uchun(self.button1_4, self.button1_3, self.button1_5, self.button2_4)
    def Button_1_5(self):
        self.Button3Uchun(self.button1_5, self.button1_4, self.button1_6, self.button2_5)
    def Button_1_6(self):
        self.Button3Uchun(self.button1_6, self.button1_5, self.button1_7, self.button2_6)
    def Button_1_7(self):
        self.Button3Uchun(self.button1_7, self.button1_6, self.button1_8, self.button2_7)

    def Button_2_1(self):
        self.Button3Uchun(self.button2_1, self.button1_1, self.button3_1, self.button2_2)
    def Button_3_1(self):
        self.Button3Uchun(self.button3_1, self.button2_1, self.button4_1, self.button3_2)
    def Button_4_1(self):
        self.Button3Uchun(self.button4_1, self.button3_1, self.button5_1, self.button4_2)
    def Button_5_1(self):
        self.Button3Uchun(self.button5_1, self.button4_1, self.button6_1, self.button5_2)
    def Button_6_1(self):
        self.Button3Uchun(self.button6_1, self.button5_1, self.button7_1, self.button6_2)
    def Button_7_1(self):
        self.Button3Uchun(self.button7_1, self.button6_1, self.button8_1, self.button7_2)

    def Button_8_2(self):
        self.Button3Uchun(self.button8_2, self.button8_1, self.button8_3, self.button7_2)
    def Button_8_3(self):
        self.Button3Uchun(self.button8_3, self.button8_2, self.button8_4, self.button7_3)
    def Button_8_4(self):
        self.Button3Uchun(self.button8_4, self.button8_3, self.button8_5, self.button7_4)
    def Button_8_5(self):
        self.Button3Uchun(self.button8_5, self.button8_4, self.button8_6, self.button7_5)
    def Button_8_6(self):
        self.Button3Uchun(self.button8_6, self.button8_5, self.button8_7, self.button7_6)
    def Button_8_7(self):
        self.Button3Uchun(self.button8_7, self.button8_6, self.button8_8, self.button7_7)

    def Button_2_8(self):
        self.Button3Uchun(self.button2_8, self.button1_8, self.button3_8, self.button2_7)
    def Button_3_8(self):
        self.Button3Uchun(self.button3_8, self.button2_8, self.button4_8, self.button3_7)
    def Button_4_8(self):
        self.Button3Uchun(self.button4_8, self.button3_8, self.button5_8, self.button4_7)
    def Button_5_8(self):
        self.Button3Uchun(self.button5_8, self.button4_8, self.button6_8, self.button5_7)
    def Button_6_8(self):
        self.Button3Uchun(self.button6_8, self.button5_8, self.button7_8, self.button6_7)
    def Button_7_8(self):
        self.Button3Uchun(self.button7_8, self.button6_8, self.button8_8, self.button7_7)
    #3tomonli tugadi
    #--------------------------------------------


    
    #bu faqat 4tomoni bor button uchun
    def Button4Uchun(self,ozi,ong,chap,past,tepa):
        if(ozi.text() != ""):
            self.list.append("1")
            for i in range(1,300,2):
                self.toq.append(i)
            for j in range(2,300,2):
                self.juft.append(j)
            if(len(self.list) in self.toq):
                self.birinchi = ozi.text()#self.button1_2.text()
            elif(len(self.list) in self.juft):
                if(int(ozi.text())+int(self.birinchi) == 10):
                    if(ong.text() == self.birinchi):
                        ong.setText("")
                        ozi.setText("")
                    elif(chap.text() == self.birinchi):
                        chap.setText("")
                        ozi.setText("")
                    elif(past.text() == self.birinchi):
                        past.setText("")
                        ozi.setText("")
                    elif(tepa.text() == self.birinchi):
                        tepa.setText("")
                        ozi.setText("")
        if(self.button1_1.text() == "" and self.button1_2.text() == "" and self.button1_3.text() == "" and self.button1_4.text() == "" and
           self.button1_5.text() == "" and self.button1_6.text() == "" and self.button1_7.text() == "" and self.button1_8.text() == "" and
           self.button2_1.text() == "" and self.button2_2.text() == "" and self.button2_3.text() == "" and self.button2_4.text() == "" and
           self.button2_5.text() == "" and self.button2_6.text() == "" and self.button2_7.text() == "" and self.button2_8.text() == "" and
           self.button3_1.text() == "" and self.button3_2.text() == "" and self.button3_3.text() == "" and self.button3_4.text() == "" and
           self.button3_5.text() == "" and self.button3_6.text() == "" and self.button3_7.text() == "" and self.button3_8.text() == "" and
           self.button4_1.text() == "" and self.button4_2.text() == "" and self.button4_3.text() == "" and self.button4_4.text() == "" and
           self.button4_5.text() == "" and self.button4_6.text() == "" and self.button4_7.text() == "" and self.button4_8.text() == "" and
           self.button5_1.text() == "" and self.button5_2.text() == "" and self.button5_3.text() == "" and self.button5_4.text() == "" and
           self.button5_5.text() == "" and self.button5_6.text() == "" and self.button5_7.text() == "" and self.button5_8.text() == "" and
           self.button6_1.text() == "" and self.button6_2.text() == "" and self.button6_3.text() == "" and self.button6_4.text() == "" and
           self.button6_5.text() == "" and self.button6_6.text() == "" and self.button6_7.text() == "" and self.button6_8.text() == "" and
           self.button7_1.text() == "" and self.button7_2.text() == "" and self.button7_3.text() == "" and self.button7_4.text() == "" and
           self.button7_5.text() == "" and self.button7_6.text() == "" and self.button7_7.text() == "" and self.button7_8.text() == "" and
           self.button8_1.text() == "" and self.button8_2.text() == "" and self.button8_3.text() == "" and self.button8_4.text() == "" and
           self.button8_5.text() == "" and self.button8_6.text() == "" and self.button8_7.text() == "" and self.button8_8.text() == ""):
            self.Oyna.setText("Siz yutdingiz!")
    
    def Button_2_2(self):
        self.Button4Uchun(self.button2_2, self.button2_3, self.button2_1, self.button3_2, self.button1_2)
    def Button_3_2(self):
        self.Button4Uchun(self.button3_2, self.button3_3, self.button3_1, self.button4_2, self.button2_2)
    def Button_4_2(self):
        self.Button4Uchun(self.button4_2, self.button4_3, self.button4_1, self.button5_2, self.button3_2)
    def Button_5_2(self):
        self.Button4Uchun(self.button5_2, self.button5_3, self.button5_1, self.button6_2, self.button4_2)
    def Button_6_2(self):
        self.Button4Uchun(self.button6_2, self.button6_3, self.button6_1, self.button7_2, self.button5_2)
    def Button_7_2(self):
        self.Button4Uchun(self.button7_2, self.button7_3, self.button7_1, self.button8_2, self.button6_2)

    def Button_2_3(self):
        self.Button4Uchun(self.button2_3, self.button2_4, self.button2_2, self.button3_3, self.button1_3)
    def Button_3_3(self):
        self.Button4Uchun(self.button3_3, self.button3_4, self.button3_2, self.button4_3, self.button2_3)
    def Button_4_3(self):
        self.Button4Uchun(self.button4_3, self.button4_4, self.button4_2, self.button5_3, self.button3_3)
    def Button_5_3(self):
        self.Button4Uchun(self.button5_3, self.button5_4, self.button5_2, self.button6_3, self.button4_3)
    def Button_6_3(self):
        self.Button4Uchun(self.button6_3, self.button6_4, self.button6_2, self.button7_3, self.button5_3)
    def Button_7_3(self):
        self.Button4Uchun(self.button7_3, self.button7_4, self.button7_2, self.button8_3, self.button6_3)

    def Button_2_4(self):
        self.Button4Uchun(self.button2_4, self.button2_5, self.button2_3, self.button3_4, self.button1_4)
    def Button_3_4(self):
        self.Button4Uchun(self.button3_4, self.button3_5, self.button3_3, self.button4_4, self.button2_4)
    def Button_4_4(self):
        self.Button4Uchun(self.button4_4, self.button4_5, self.button4_3, self.button5_4, self.button3_4)
    def Button_5_4(self):
        self.Button4Uchun(self.button5_4, self.button5_5, self.button5_3, self.button6_4, self.button4_4)
    def Button_6_4(self):
        self.Button4Uchun(self.button6_4, self.button6_5, self.button6_3, self.button7_4, self.button5_4)
    def Button_7_4(self):
        self.Button4Uchun(self.button7_4, self.button7_5, self.button7_3, self.button8_4, self.button6_4)

    def Button_2_5(self):
        self.Button4Uchun(self.button2_5, self.button2_6, self.button2_4, self.button3_5, self.button1_5)
    def Button_3_5(self):
        self.Button4Uchun(self.button3_5, self.button3_6, self.button3_4, self.button4_5, self.button2_5)
    def Button_4_5(self):
        self.Button4Uchun(self.button4_5, self.button4_6, self.button4_4, self.button5_5, self.button3_5)
    def Button_5_5(self):
        self.Button4Uchun(self.button5_5, self.button5_6, self.button5_4, self.button6_5, self.button4_5)
    def Button_6_5(self):
        self.Button4Uchun(self.button6_5, self.button6_6, self.button6_4, self.button7_5, self.button5_5)
    def Button_7_5(self):
        self.Button4Uchun(self.button7_5, self.button7_6, self.button7_4, self.button8_5, self.button6_5)

    def Button_2_6(self):
        self.Button4Uchun(self.button2_6, self.button2_7, self.button2_5, self.button3_6, self.button1_6)
    def Button_3_6(self):
        self.Button4Uchun(self.button3_6, self.button3_7, self.button3_5, self.button4_6, self.button2_6)
    def Button_4_6(self):
        self.Button4Uchun(self.button4_6, self.button4_7, self.button4_5, self.button5_6, self.button3_6)
    def Button_5_6(self):
        self.Button4Uchun(self.button5_6, self.button5_7, self.button5_5, self.button6_6, self.button4_6)
    def Button_6_6(self):
        self.Button4Uchun(self.button6_6, self.button6_7, self.button6_5, self.button7_6, self.button5_6)
    def Button_7_6(self):
        self.Button4Uchun(self.button7_6, self.button7_7, self.button7_5, self.button8_6, self.button6_6)

    def Button_2_7(self):
        self.Button4Uchun(self.button2_7, self.button2_8, self.button2_6, self.button3_7, self.button1_7)
    def Button_3_7(self):
        self.Button4Uchun(self.button3_7, self.button3_8, self.button3_6, self.button4_7, self.button2_7)
    def Button_4_7(self):
        self.Button4Uchun(self.button4_7, self.button4_8, self.button4_6, self.button5_7, self.button3_7)
    def Button_5_7(self):
        self.Button4Uchun(self.button5_7, self.button5_8, self.button5_6, self.button6_7, self.button4_7)
    def Button_6_7(self):
        self.Button4Uchun(self.button6_7, self.button6_8, self.button6_6, self.button7_7, self.button5_7)
    def Button_7_7(self):
        self.Button4Uchun(self.button7_7, self.button7_8, self.button7_6, self.button8_7, self.button6_7)
    

            
    def YangilashUchun(self):
        self.button1_1.setText("1") 
        self.button1_2.setText("8")
        self.button1_3.setText("6")
        self.button1_4.setText("3")
        self.button1_5.setText("5") 
        self.button1_6.setText("9")
        self.button1_7.setText("9")
        self.button1_8.setText("7")
        self.button2_1.setText("6") 
        self.button2_2.setText("7")
        self.button2_3.setText("7")
        self.button2_4.setText("3")
        self.button2_5.setText("3") 
        self.button2_6.setText("9") 
        self.button2_7.setText("5") 
        self.button2_8.setText("2")
        self.button3_1.setText("2") 
        self.button3_2.setText("6") 
        self.button3_3.setText("1") 
        self.button3_4.setText("4")
        self.button3_5.setText("9") 
        self.button3_6.setText("5") 
        self.button3_7.setText("2") 
        self.button3_8.setText("5")
        self.button4_1.setText("2") 
        self.button4_2.setText("4")
        self.button4_3.setText("7")
        self.button4_4.setText("7")
        self.button4_5.setText("6") 
        self.button4_6.setText("5")
        self.button4_7.setText("6")
        self.button4_8.setText("7")
        self.button5_1.setText("4") 
        self.button5_2.setText("5")
        self.button5_3.setText("1")
        self.button5_4.setText("5")
        self.button5_5.setText("8") 
        self.button5_6.setText("7") 
        self.button5_7.setText("1") 
        self.button5_8.setText("9")
        self.button6_1.setText("1") 
        self.button6_2.setText("4") 
        self.button6_3.setText("1") 
        self.button6_4.setText("1")
        self.button6_5.setText("2") 
        self.button6_6.setText("4") 
        self.button6_7.setText("4") 
        self.button6_8.setText("9")
        self.button7_1.setText("5")
        self.button7_2.setText("8")
        self.button7_3.setText("3")
        self.button7_4.setText("6")
        self.button7_5.setText("8")
        self.button7_6.setText("6")
        self.button7_7.setText("4")
        self.button7_8.setText("3")
        self.button8_1.setText("9")
        self.button8_2.setText("3")
        self.button8_3.setText("8")
        self.button8_4.setText("6")
        self.button8_5.setText("3")
        self.button8_6.setText("1")
        self.button8_7.setText("4")
        self.button8_8.setText("9")
        






    #------------------------------------------

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(870, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button1_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_1.setGeometry(QtCore.QRect(70, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_1.setFont(font)
        self.button1_1.setObjectName("button1_1")
        self.button1_1.clicked.connect(self.Button_1_1)


        self.button1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_2.setGeometry(QtCore.QRect(120, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_2.setFont(font)
        self.button1_2.setObjectName("button1_2")
        self.button1_2.clicked.connect(self.Button_1_2)


        self.button1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_3.setGeometry(QtCore.QRect(170, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_3.setFont(font)
        self.button1_3.setObjectName("button1_3")
        self.button1_3.clicked.connect(self.Button_1_3)


        self.button1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_4.setGeometry(QtCore.QRect(220, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_4.setFont(font)
        self.button1_4.setObjectName("button1_4")
        self.button1_4.clicked.connect(self.Button_1_4)


        self.button1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_5.setGeometry(QtCore.QRect(270, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_5.setFont(font)
        self.button1_5.setObjectName("button1_5")
        self.button1_5.clicked.connect(self.Button_1_5)


        self.button1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_6.setGeometry(QtCore.QRect(320, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_6.setFont(font)
        self.button1_6.setObjectName("button1_6")
        self.button1_6.clicked.connect(self.Button_1_6)


        self.button1_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_7.setGeometry(QtCore.QRect(370, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_7.setFont(font)
        self.button1_7.setObjectName("button1_7")
        self.button1_7.clicked.connect(self.Button_1_7)


        self.button1_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button1_8.setGeometry(QtCore.QRect(420, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button1_8.setFont(font)
        self.button1_8.setObjectName("button1_8")
        self.button1_8.clicked.connect(self.Button_1_8)


        self.button2_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_8.setGeometry(QtCore.QRect(420, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_8.setFont(font)
        self.button2_8.setObjectName("button2_8")
        self.button2_8.clicked.connect(self.Button_2_8)


        self.button2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_1.setGeometry(QtCore.QRect(70, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_1.setFont(font)
        self.button2_1.setObjectName("button2_1")
        self.button2_1.clicked.connect(self.Button_2_1)


        self.button2_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_7.setGeometry(QtCore.QRect(370, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_7.setFont(font)
        self.button2_7.setObjectName("button2_7")
        self.button2_7.clicked.connect(self.Button_2_7)


        self.button2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_4.setGeometry(QtCore.QRect(220, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_4.setFont(font)
        self.button2_4.setObjectName("button2_4")
        self.button2_4.clicked.connect(self.Button_2_4)


        self.button2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_3.setGeometry(QtCore.QRect(170, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_3.setFont(font)
        self.button2_3.setObjectName("button2_3")
        self.button2_3.clicked.connect(self.Button_2_3)


        self.button2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_5.setGeometry(QtCore.QRect(270, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_5.setFont(font)
        self.button2_5.setObjectName("button2_5")
        self.button2_5.clicked.connect(self.Button_2_5)


        self.button2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_2.setGeometry(QtCore.QRect(120, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_2.setFont(font)
        self.button2_2.setObjectName("button2_2")
        self.button2_2.clicked.connect(self.Button_2_2)


        self.button2_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button2_6.setGeometry(QtCore.QRect(320, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button2_6.setFont(font)
        self.button2_6.setObjectName("button2_6")
        self.button2_6.clicked.connect(self.Button_2_6)


        self.button3_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_8.setGeometry(QtCore.QRect(420, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_8.setFont(font)
        self.button3_8.setObjectName("button3_8")
        self.button3_8.clicked.connect(self.Button_3_8)


        self.button3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_1.setGeometry(QtCore.QRect(70, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_1.setFont(font)
        self.button3_1.setObjectName("button3_1")
        self.button3_1.clicked.connect(self.Button_3_1)


        self.button4_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_8.setGeometry(QtCore.QRect(420, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_8.setFont(font)
        self.button4_8.setObjectName("button4_8")
        self.button4_8.clicked.connect(self.Button_4_8)


        self.button4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_4.setGeometry(QtCore.QRect(220, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_4.setFont(font)
        self.button4_4.setObjectName("button4_4")
        self.button4_4.clicked.connect(self.Button_4_4) #20


        self.button3_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_7.setGeometry(QtCore.QRect(370, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_7.setFont(font)
        self.button3_7.setObjectName("button3_7")
        self.button3_7.clicked.connect(self.Button_3_7)


        self.button4_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_7.setGeometry(QtCore.QRect(370, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_7.setFont(font)
        self.button4_7.setObjectName("button4_7")
        self.button4_7.clicked.connect(self.Button_4_7)


        self.button3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_4.setGeometry(QtCore.QRect(220, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_4.setFont(font)
        self.button3_4.setObjectName("button3_4")
        self.button3_4.clicked.connect(self.Button_3_4)


        self.button4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_2.setGeometry(QtCore.QRect(120, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_2.setFont(font)
        self.button4_2.setObjectName("button4_2")
        self.button4_2.clicked.connect(self.Button_4_2)


        self.button3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_3.setGeometry(QtCore.QRect(170, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_3.setFont(font)
        self.button3_3.setObjectName("button3_3")
        self.button3_3.clicked.connect(self.Button_3_3)


        self.button3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_5.setGeometry(QtCore.QRect(270, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_5.setFont(font)
        self.button3_5.setObjectName("button3_5")
        self.button3_5.clicked.connect(self.Button_3_5)


        self.button4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_3.setGeometry(QtCore.QRect(170, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_3.setFont(font)
        self.button4_3.setObjectName("button4_3")
        self.button4_3.clicked.connect(self.Button_4_3)


        self.button3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_2.setGeometry(QtCore.QRect(120, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_2.setFont(font)
        self.button3_2.setObjectName("button3_2")
        self.button3_2.clicked.connect(self.Button_3_2)


        self.button4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_5.setGeometry(QtCore.QRect(270, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_5.setFont(font)
        self.button4_5.setObjectName("button4_5")
        self.button4_5.clicked.connect(self.Button_4_5)


        self.button3_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button3_6.setGeometry(QtCore.QRect(320, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button3_6.setFont(font)
        self.button3_6.setObjectName("button3_6")
        self.button3_6.clicked.connect(self.Button_3_6)


        self.button4_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_6.setGeometry(QtCore.QRect(320, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_6.setFont(font)
        self.button4_6.setObjectName("button4_6")
        self.button4_6.clicked.connect(self.Button_4_6)


        self.button4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button4_1.setGeometry(QtCore.QRect(70, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button4_1.setFont(font)
        self.button4_1.setObjectName("button4_1")
        self.button4_1.clicked.connect(self.Button_4_1)


        self.button5_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_7.setGeometry(QtCore.QRect(370, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_7.setFont(font)
        self.button5_7.setObjectName("button5_7")
        self.button5_7.clicked.connect(self.Button_5_7)


        self.button8_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_7.setGeometry(QtCore.QRect(370, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_7.setFont(font)
        self.button8_7.setObjectName("button8_7")
        self.button8_7.clicked.connect(self.Button_8_7)


        self.button7_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_4.setGeometry(QtCore.QRect(220, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_4.setFont(font)
        self.button7_4.setObjectName("button7_4")
        self.button7_4.clicked.connect(self.Button_7_4)


        self.button5_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_5.setGeometry(QtCore.QRect(270, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_5.setFont(font)
        self.button5_5.setObjectName("button5_5")
        self.button5_5.clicked.connect(self.Button_5_5)


        self.button7_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_1.setGeometry(QtCore.QRect(70, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_1.setFont(font)
        self.button7_1.setObjectName("button7_1")
        self.button7_1.clicked.connect(self.Button_7_1)


        self.button7_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_7.setGeometry(QtCore.QRect(370, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_7.setFont(font)
        self.button7_7.setObjectName("button7_7")
        self.button7_7.clicked.connect(self.Button_7_7)


        self.button7_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_2.setGeometry(QtCore.QRect(120, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_2.setFont(font)
        self.button7_2.setObjectName("button7_2")
        self.button7_2.clicked.connect(self.Button_7_2)


        self.button8_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_4.setGeometry(QtCore.QRect(220, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_4.setFont(font)
        self.button8_4.setObjectName("button8_4")
        self.button8_4.clicked.connect(self.Button_8_4)


        self.button8_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_5.setGeometry(QtCore.QRect(270, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_5.setFont(font)
        self.button8_5.setObjectName("button8_5")
        self.button8_5.clicked.connect(self.Button_8_5)


        self.button6_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_6.setGeometry(QtCore.QRect(320, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_6.setFont(font)
        self.button6_6.setObjectName("button6_6")
        self.button6_6.clicked.connect(self.Button_6_6)


        self.button8_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_8.setGeometry(QtCore.QRect(420, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_8.setFont(font)
        self.button8_8.setObjectName("button8_8")
        self.button8_8.clicked.connect(self.Button_8_8)


        self.button7_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_3.setGeometry(QtCore.QRect(170, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_3.setFont(font)
        self.button7_3.setObjectName("button7_3")
        self.button7_3.clicked.connect(self.Button_7_3)


        self.button8_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_3.setGeometry(QtCore.QRect(170, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_3.setFont(font)
        self.button8_3.setObjectName("button8_3")
        self.button8_3.clicked.connect(self.Button_8_3)


        self.button6_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_3.setGeometry(QtCore.QRect(170, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_3.setFont(font)
        self.button6_3.setObjectName("button6_3")
        self.button6_3.clicked.connect(self.Button_6_3)


        self.button6_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_1.setGeometry(QtCore.QRect(70, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_1.setFont(font)
        self.button6_1.setObjectName("button6_1")
        self.button6_1.clicked.connect(self.Button_6_1)


        self.button6_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_8.setGeometry(QtCore.QRect(420, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_8.setFont(font)
        self.button6_8.setObjectName("button6_8")
        self.button6_8.clicked.connect(self.Button_6_8)


        self.button8_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_6.setGeometry(QtCore.QRect(320, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_6.setFont(font)
        self.button8_6.setObjectName("button8_6")
        self.button8_6.clicked.connect(self.Button_8_6)


        self.button7_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_6.setGeometry(QtCore.QRect(320, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_6.setFont(font)
        self.button7_6.setObjectName("button7_6")
        self.button7_6.clicked.connect(self.Button_7_6)


        self.button5_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_8.setGeometry(QtCore.QRect(420, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_8.setFont(font)
        self.button5_8.setObjectName("button5_8")
        self.button5_8.clicked.connect(self.Button_5_8)


        self.button5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_1.setGeometry(QtCore.QRect(70, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_1.setFont(font)
        self.button5_1.setObjectName("button5_1") 
        self.button5_1.clicked.connect(self.Button_5_1)


        self.button5_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_4.setGeometry(QtCore.QRect(220, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_4.setFont(font)
        self.button5_4.setObjectName("button5_4")
        self.button5_4.clicked.connect(self.Button_5_4)


        self.button5_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_6.setGeometry(QtCore.QRect(320, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_6.setFont(font)
        self.button5_6.setObjectName("button5_6")
        self.button5_6.clicked.connect(self.Button_5_6)


        self.button6_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_5.setGeometry(QtCore.QRect(270, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_5.setFont(font)
        self.button6_5.setObjectName("button6_5")
        self.button6_5.clicked.connect(self.Button_6_5)


        self.button5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_3.setGeometry(QtCore.QRect(170, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_3.setFont(font)
        self.button5_3.setObjectName("button5_3")
        self.button5_3.clicked.connect(self.Button_5_3)


        self.button6_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_4.setGeometry(QtCore.QRect(220, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_4.setFont(font)
        self.button6_4.setObjectName("button6_4")
        self.button6_4.clicked.connect(self.Button_6_4)


        self.button6_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_7.setGeometry(QtCore.QRect(370, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_7.setFont(font)
        self.button6_7.setObjectName("button6_7")
        self.button6_7.clicked.connect(self.Button_6_7)


        self.button6_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button6_2.setGeometry(QtCore.QRect(120, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button6_2.setFont(font)
        self.button6_2.setObjectName("button6_2")
        self.button6_2.clicked.connect(self.Button_6_2)


        self.button7_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_5.setGeometry(QtCore.QRect(270, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_5.setFont(font)
        self.button7_5.setObjectName("button7_5")
        self.button7_5.clicked.connect(self.Button_7_5)


        self.button8_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_1.setGeometry(QtCore.QRect(70, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_1.setFont(font)
        self.button8_1.setObjectName("button8_1")
        self.button8_1.clicked.connect(self.Button_8_1)


        self.button7_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button7_8.setGeometry(QtCore.QRect(420, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button7_8.setFont(font)
        self.button7_8.setObjectName("button7_8")
        self.button7_8.clicked.connect(self.Button_7_8)


        self.button5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button5_2.setGeometry(QtCore.QRect(120, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button5_2.setFont(font)
        self.button5_2.setObjectName("button5_2")
        self.button5_2.clicked.connect(self.Button_5_2)


        self.button8_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button8_2.setGeometry(QtCore.QRect(120, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.button8_2.setFont(font)
        self.button8_2.setObjectName("button8_2")
        self.button8_2.clicked.connect(self.Button_8_2)


        self.garizont1 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont1.setGeometry(QtCore.QRect(490, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont1.setFont(font)
        self.garizont1.setObjectName("garizont1")
        self.garizont1.clicked.connect(self.Garizontal1)


        self.garizont2 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont2.setGeometry(QtCore.QRect(490, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont2.setFont(font)
        self.garizont2.setObjectName("garizont2")

        self.garizont2.clicked.connect(self.Garizontal2)
        self.garizont6 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont6.setGeometry(QtCore.QRect(490, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont6.setFont(font)
        self.garizont6.setObjectName("garizont6")
        self.garizont6.clicked.connect(self.Garizontal6)


        self.garizont5 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont5.setGeometry(QtCore.QRect(490, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont5.setFont(font)
        self.garizont5.setObjectName("garizont5")
        self.garizont5.clicked.connect(self.Garizontal5)


        self.garizont8 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont8.setGeometry(QtCore.QRect(490, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont8.setFont(font)
        self.garizont8.setObjectName("garizont8")
        self.garizont8.clicked.connect(self.Garizontal8)


        self.garizont7 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont7.setGeometry(QtCore.QRect(490, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont7.setFont(font)
        self.garizont7.setObjectName("garizont7")
        self.garizont7.clicked.connect(self.Garizontal7)


        self.garizont3 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont3.setGeometry(QtCore.QRect(490, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont3.setFont(font)
        self.garizont3.setObjectName("garizont3")
        self.garizont3.clicked.connect(self.Garizontal3)
        
        self.garizont4 = QtWidgets.QPushButton(self.centralwidget)
        self.garizont4.setGeometry(QtCore.QRect(490, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.garizont4.setFont(font)
        self.garizont4.setObjectName("garizont4")
        self.garizont4.clicked.connect(self.Garizontal4)


        self.vertikal3 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal3.setGeometry(QtCore.QRect(170, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal3.setFont(font)
        self.vertikal3.setObjectName("vertikal3")
        self.vertikal3.clicked.connect(self.Vertikal3)


        self.vertikal5 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal5.setGeometry(QtCore.QRect(270, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal5.setFont(font)
        self.vertikal5.setObjectName("vertikal5")
        self.vertikal5.clicked.connect(self.Vertikal5)


        self.vertikal8 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal8.setGeometry(QtCore.QRect(420, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal8.setFont(font)
        self.vertikal8.setObjectName("vertikal8")
        self.vertikal8.clicked.connect(self.Vertikal8)


        self.vertikal1 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal1.setGeometry(QtCore.QRect(70, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal1.setFont(font)
        self.vertikal1.setObjectName("vertikal1")
        self.vertikal1.clicked.connect(self.Vertikal1)


        self.vertikal7 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal7.setGeometry(QtCore.QRect(370, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal7.setFont(font)
        self.vertikal7.setObjectName("vertikal7")
        self.vertikal7.clicked.connect(self.Vertikal7)


        self.vertikal6 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal6.setGeometry(QtCore.QRect(320, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal6.setFont(font)
        self.vertikal6.setObjectName("vertikal6")
        self.vertikal6.clicked.connect(self.Vertikal6)


        self.vertikal4 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal4.setGeometry(QtCore.QRect(220, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal4.setFont(font)
        self.vertikal4.setObjectName("vertikal4")
        self.vertikal4.clicked.connect(self.Vertikal4)


        self.vertikal2 = QtWidgets.QPushButton(self.centralwidget)
        self.vertikal2.setGeometry(QtCore.QRect(120, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.vertikal2.setFont(font)
        self.vertikal2.setObjectName("vertikal2")
        self.vertikal2.clicked.connect(self.Vertikal2)


        self.Yangilash = QtWidgets.QPushButton(self.centralwidget)
        self.Yangilash.setGeometry(QtCore.QRect(490, 510, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.Yangilash.setFont(font)
        self.Yangilash.setObjectName("Yangilash")
        self.Yangilash.clicked.connect(self.YangilashUchun)

        self.Oyna = QtWidgets.QLabel(self.centralwidget)
        self.Oyna.setGeometry(QtCore.QRect(200, 580, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(16)
        self.Oyna.setFont(font)
        self.Oyna.setText("")
        self.Oyna.setObjectName("Oyna")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 870, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button1_1.setText(_translate("MainWindow", "8"))
        self.button1_2.setText(_translate("MainWindow", "2"))
        self.button1_3.setText(_translate("MainWindow", "3"))
        self.button1_4.setText(_translate("MainWindow", "4"))
        self.button1_5.setText(_translate("MainWindow", "5"))
        self.button1_6.setText(_translate("MainWindow", "6"))
        self.button1_7.setText(_translate("MainWindow", "7"))

        self.button1_8.setText(_translate("MainWindow", "5"))
        self.button2_8.setText(_translate("MainWindow", "2"))

        self.button2_1.setText(_translate("MainWindow", "8"))
        self.button2_7.setText(_translate("MainWindow", "7"))
        self.button2_4.setText(_translate("MainWindow", "4"))
        self.button2_3.setText(_translate("MainWindow", "3"))
        self.button2_5.setText(_translate("MainWindow", "5"))
        self.button2_2.setText(_translate("MainWindow", "5"))
        self.button2_6.setText(_translate("MainWindow", "6"))

        self.button3_8.setText(_translate("MainWindow", "9"))

        self.button3_1.setText(_translate("MainWindow", "1"))

        self.button4_8.setText(_translate("MainWindow", "4"))

        self.button4_4.setText(_translate("MainWindow", "6"))
        self.button3_7.setText(_translate("MainWindow", "7"))
        self.button4_7.setText(_translate("MainWindow", "3"))
        self.button3_4.setText(_translate("MainWindow", "1"))
        self.button4_2.setText(_translate("MainWindow", "9"))
        self.button3_3.setText(_translate("MainWindow", "5"))
        self.button3_5.setText(_translate("MainWindow", "5"))
        self.button4_3.setText(_translate("MainWindow", "3"))
        self.button3_2.setText(_translate("MainWindow", "7"))
        self.button4_5.setText(_translate("MainWindow", "5"))
        self.button3_6.setText(_translate("MainWindow", "5"))
        self.button4_6.setText(_translate("MainWindow", "6"))
        self.button4_1.setText(_translate("MainWindow", "1"))
        self.button5_7.setText(_translate("MainWindow", "9"))
        self.button8_7.setText(_translate("MainWindow", "7"))
        self.button7_4.setText(_translate("MainWindow", "4"))
        self.button5_5.setText(_translate("MainWindow", "3"))
        self.button7_1.setText(_translate("MainWindow", "1"))
        self.button7_7.setText(_translate("MainWindow", "9"))
        self.button7_2.setText(_translate("MainWindow", "2"))
        self.button8_4.setText(_translate("MainWindow", "8"))
        self.button8_5.setText(_translate("MainWindow", "5"))
        self.button6_6.setText(_translate("MainWindow", "5"))

        self.button8_8.setText(_translate("MainWindow", "8"))

        self.button7_3.setText(_translate("MainWindow", "2"))
        self.button8_3.setText(_translate("MainWindow", "3"))
        self.button6_3.setText(_translate("MainWindow", "7"))
        self.button6_1.setText(_translate("MainWindow", "1"))

        self.button6_8.setText(_translate("MainWindow", "9"))

        self.button8_6.setText(_translate("MainWindow", "6"))
        self.button7_6.setText(_translate("MainWindow", "4"))

        self.button5_8.setText(_translate("MainWindow", "5"))

        self.button5_1.setText(_translate("MainWindow", "5"))
        self.button5_4.setText(_translate("MainWindow", "4"))
        self.button5_6.setText(_translate("MainWindow", "6"))
        self.button6_5.setText(_translate("MainWindow", "5"))
        self.button5_3.setText(_translate("MainWindow", "5"))
        self.button6_4.setText(_translate("MainWindow", "4"))
        self.button6_7.setText(_translate("MainWindow", "6"))
        self.button6_2.setText(_translate("MainWindow", "2"))
        self.button7_5.setText(_translate("MainWindow", "9"))
        self.button8_1.setText(_translate("MainWindow", "1"))
        
        self.button7_8.setText(_translate("MainWindow", "8"))

        self.button5_2.setText(_translate("MainWindow", "6"))
        self.button8_2.setText(_translate("MainWindow", "4"))
        self.garizont1.setText(_translate("MainWindow", "⬅️"))
        self.garizont2.setText(_translate("MainWindow", "⬅️"))
        self.garizont6.setText(_translate("MainWindow", "⬅️"))
        self.garizont5.setText(_translate("MainWindow", "⬅️"))
        self.garizont8.setText(_translate("MainWindow", "⬅️"))
        self.garizont7.setText(_translate("MainWindow", "⬅️"))
        self.garizont3.setText(_translate("MainWindow", "⬅️"))
        self.garizont4.setText(_translate("MainWindow", "⬅️"))
        self.vertikal3.setText(_translate("MainWindow", "⬆️"))
        self.vertikal5.setText(_translate("MainWindow", "⬆️"))
        self.vertikal8.setText(_translate("MainWindow", "⬆️"))
        self.vertikal1.setText(_translate("MainWindow", "⬆️"))
        self.vertikal7.setText(_translate("MainWindow", "⬆️"))
        self.vertikal6.setText(_translate("MainWindow", "⬆️"))
        self.vertikal4.setText(_translate("MainWindow", "⬆️"))
        self.vertikal2.setText(_translate("MainWindow", "⬆️"))
        self.Yangilash.setText(_translate("MainWindow", "🔄"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
